import './globals.css'
import {  Rubik } from 'next/font/google'
import Navbar from '../Components/Navbar'

const rubik = Rubik({weight:'500', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${rubik.className} lg:mx-28 ` }>
      <Navbar/>
        {children}
        </body>
    </html>
  )
}
